# Generated by Django 3.1.5 on 2021-01-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datesprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='datesprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datesprofile',
            name='interests',
            field=models.ManyToManyField(blank=True, null=True, related_name='profiles_datesprofile_related', to='profiles.Interest'),
        ),
        migrations.AlterField(
            model_name='datesprofile',
            name='sexual_orientation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='friendsprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='friendsprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='friendsprofile',
            name='interests',
            field=models.ManyToManyField(blank=True, null=True, related_name='profiles_friendsprofile_related', to='profiles.Interest'),
        ),
    ]
