# Generated by Django 3.1.5 on 2021-01-30 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210130_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nationality',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='nationality',
            name='object_id',
        ),
        migrations.AddField(
            model_name='friendsprofile',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.nationality'),
        ),
    ]
