# Generated by Django 3.1.5 on 2021-02-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20210201_1842'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='acquaintancerequest',
            name='profiles.AcquaintanceRequests',
        ),
        migrations.RemoveConstraint(
            model_name='match',
            name='profiles.Matches',
        ),
        migrations.RenameField(
            model_name='acquaintancerequest',
            old_name='date',
            new_name='request_date',
        ),
        migrations.RenameField(
            model_name='acquaintancerequest',
            old_name='content_type',
            new_name='request_type',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='date',
            new_name='match_date',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='content_type',
            new_name='match_type',
        ),
        migrations.AlterField(
            model_name='friendsprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='acquaintancerequest',
            constraint=models.UniqueConstraint(fields=('request_type', 'sender_object_id', 'receiver_object_id'), name='profiles.AcquaintanceRequests'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('match_type', 'initiator_object_id', 'confirmer_object_id'), name='profiles.Matches'),
        ),
    ]
