# Generated by Django 3.1.5 on 2021-02-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20210202_2240'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='acquaintancerequest',
            name='profiles.AcquaintanceRequests',
        ),
        migrations.RemoveConstraint(
            model_name='match',
            name='profiles.Matches',
        ),
        migrations.RenameField(
            model_name='acquaintancerequest',
            old_name='request_type',
            new_name='content_type',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='match_type',
            new_name='content_type',
        ),
        migrations.AddConstraint(
            model_name='acquaintancerequest',
            constraint=models.UniqueConstraint(fields=('content_type', 'sender_object_id', 'receiver_object_id'), name='profiles.AcquaintanceRequests'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('content_type', 'initiator_object_id', 'confirmer_object_id'), name='profiles.Matches'),
        ),
    ]
